### ISSUE TITLE
build issues/solutions

### ISSUE THREAD

**Issue by hughperkins** [torch/torch.github.io#12]
Hi,

Whilst installing torch:

1. in the specific, installer couldnt find 'torchwrap.lua' whilst installing torch package, so I ran the following by hand, from `~/torch/pkg/torch` directory:
```
LUA_PATH="$LUA_PATH;?.lua" luarocks make rocks/torch-scm-1.rockspec
```
=> this package then built ok.  Maybe might consider editing line 81 of install.sh in a similar manner?
2. in the generic, the installation ran to completion, with no particular errors, simply didnt work at the end ;-)  Perhaps could be worth considering adding to the top of install.sh:
```
set -e
set -x
```
- the first makes the script stop on any error
- the second writes each command before executing it, so we can see where errors lie

Note that with `set -e` activated, it's necessary to do something about about line 63, eg put `set +e` before it, and `set -e` after it.

**Comment by hughperkins** [comment]
Next up: ipython
- it's not installed by the install_deps script
- but it is required by install.sh (at least, it is, if one wants install.sh to run cleanly, eg with `set -e` set
- perhaps it could be worth considering either making ipython optional, eg 'IPYTHON=1 ./install.sh', or else adding it to the install_deps script
   - my guess is that adding it to install_deps script fits in best perhaps with current installation philosophy of installing everything for the user easily?

**Comment by hughperkins** [comment]
Finally ;-)  If user answers 'no' to the 'do you want to append to bashrc' question, maybe output the env settings to a script like 'setenv.sh' or 'activate.sh' or similra, in the ~/torch directory.  It's a small thing, and I suppose most people answer 'yes', but I like to keep my bashrc clean ;-)

**Comment by soumith** [comment]
@hughperkins Looking at this issue, the issue on char-rnn and the issue on nngraph, I think the first step that went wrong (that gave rise to pretty much all the other issues) is that you have an alternative lua/luajit/luarocks already installed on your machine.

We ship with our own luajit/luarocks which pick up our paths. If you have ~/torch/install/bin as the first priority in your $PATH by putting it all the way to the front, then you'd likely have a peaceful process.

Also, when you say no, we do print out the manual instructions:
https://github.com/torch/distro/blob/master/install.sh#L168

**Comment by hughperkins** [comment]
> We ship with our own luajit/luarocks which pick up our paths. If you have ~/torch/install/bin as the first priority in your $PATH by putting it all the way to the front, then you'd likely have a peaceful process.

Hmmm, could be :-)

**Comment by hughperkins** [comment]
Ok, I see, you have your own luarocks config at `install/etc/luarocks/config.lua`.  Somehow maybe the install.sh script can perhaps force the usage of this configuration perhaps?  At least point out its existence :-)

for the other issues above, I've sent pull requests :-)

**Comment by hughperkins** [comment]
Seems you can set this using LUAROCKS_CONFIG .  pullrequest incoming ;-)
