### ISSUE TITLE
Liquid Exception: Liquid syntax error: Unknown tag 'gist' in torch.github.io-master/blog/_posts/2015-07-30-cifar.md

### ISSUE THREAD

**Issue by yeison** [torch/torch.github.io#32]
I'm not very familiar with Ruby. I'm running into this issue with jekyll

  Liquid Exception: Liquid syntax error: Unknown tag 'gist' in torch.github.io-master/blog/_posts/2015-07-30-cifar.md
jekyll 3.0.1 | Error:  Liquid syntax error: Unknown tag 'gist'
ymb:torch.github.io-master yeison$ vim _config.yml 
ymb:torch.github.io-master yeison$ jekyll serve -w
Configuration file: torch.github.io-master/_config.yml
            Source:torch.github.io-master
       Destination: torch.github.io-master/_site
 Incremental build: disabled. Enable with --incremental

**Comment by soumith** [comment]
i'm not sure what you are trying to do. I dont actually know how to run this site locally, I just rely on github pages to render it. This site layout itself was forked and shamelessly modified from https://github.com/facebook/flow/tree/gh-pages

**Comment by szagoruyko** [comment]
`gem install jekyll-gist` I guess?

**Comment by yeison** [comment]
I tried installing jekyll-gist.  It was still failing.  That's very unexpected because it seems like it should work.  Anyway, I was able to run the site locally by commenting out all of the gists.  They were just blogposts so it was fine in the end.  I just wanted to read the tutorials offline.
