### ISSUE TITLE
Not able to load modules in torch

### ISSUE THREAD

**Issue by shimaalizadeh** [torch/torch.github.io#39]
I am no longer able to load modules such as 'torch'. It gives me this error:

th> require 'torch'
/Users/shima/torch/install/share/lua/5.1/trepl/init.lua:384: loop or previous error loading module 'torch'
stack traceback:
	[C]: in function 'error'
	/Users/shima/torch/install/share/lua/5.1/trepl/init.lua:384: in function 'require'
	[string "_RESULT={require 'torch'}"]:1: in main chunk
	[C]: in function 'xpcall'
	/Users/shima/torch/install/share/lua/5.1/trepl/init.lua:651: in function 'repl'
	...hima/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:199: in main chunk
	[C]: at 0x0100f0cbd0

Could you help me solve this problem? I highly appreciate that!

**Comment by soumith** [comment]
Could you post this to our google groups here: https://groups.google.com/forum/#!forum/torch7 , we only use this github issues for bug tracking. We'll happily reply there. Thanks.
