### ISSUE TITLE
Error in install-deps script

### ISSUE THREAD

**Issue by iftekharanam** [torch/torch.github.io#42]
Line 95 of the install-deps uses "VERS" instead of VERSION, which causes the CentOS version check to fail. I am trying to install torch on an HPC cluster running CentOS 6.6. Since I don't have sudo privilege, I tried to install it inside my directory changing the version. ${centos_major_version} was empty and the version check was failing even after I changed the version number.

**Comment by soumith** [comment]
fixed via https://github.com/torch/distro/commit/ffb71309eaf0224db6bd4d0a5362b5382ec232ae
