### ISSUE TITLE
error while installing torch on install-deps

### ISSUE THREAD

**Issue by WenchenLi** [torch/torch.github.io#58]
Hi,
I rm  old torch and install  from scratch on ubuntu16.04 but always got
```
nodejs is already the newest version (4.4.7-1nodesource1~trusty1).
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 nodejs : Conflicts: npm
E: Unable to correct problems, you have held broken packages.
```

according to stackoverflow posts [here](http://serverfault.com/questions/529385/the-following-packages-have-unmet-dependencies-nodejs-conflicts-npm) , I think on line 151 of file install-deps, npm could be removed since install nodejs includes install npm now.

please correct me if im wrong, thanks!

**Comment by soumith** [comment]
thanks for the report. we do not need to install nodejs anymore, so i've removed it completely from the script: https://github.com/torch/distro/commit/2b0b038f27f48507fbc892389942293683ab4a6f
