### ISSUE TITLE
Referenced FPGA Backend Missing in Action

### ISSUE THREAD

**Issue by joshuagruenstein** [torch/torch.github.io#63]
On Torch's homepage, the following claim is made:

> Embeddable, with ports to iOS, Android and FPGA backends

Although there do exist functional ports to [iOS](https://github.com/clementfarabet/torch-ios) and [Android](https://github.com/soumith/torch-android), I cannot find any maintained FPGA backends for Torch.  If there does exist such a backend, it is not mentioned in any of Torch's documentation besides the homepage.  Thus, it seems to me that either the homepage should be updated to remove reference to an FPGA backend, or the documentation should be updated with a link to a specific implementation.  Thanks.

**Comment by soumith** [comment]
e-lab headed by Eugenio Culuricello used to maitain an FPGA backend for Torch: https://e-lab.github.io

Looks like they might have taken it offline (they started a company around this)

**Comment by joshuagruenstein** [comment]
If this is the case, shouldn't the reference to the FPGA backend be removed?
